### ISSUE TITLE
Not sure how to add dependency into android studio and integrate cheque scanning api 

### ISSUE THREAD

**Issue by suzanneong3** [doo/scanbot-sdk-example-android#85]
Hi when i try to add the dependency 
compile "io.scanbot:sdk-package-3:1.35.0"
it gives me an error : Failed to resolve: io.scanbot:sdk-package-3:1.35.0
can someone teach me how to get the correct dependency for the cheque scanning api ? and whr is the right page i should look at to integrate the cheque api

**Comment by tailsu** [comment]
Have you done each step in the [Getting started](https://github.com/doo/scanbot-sdk-example-android/wiki/Getting-started) section?

**Comment by suzanneong3** [comment]
Yes ive followed the steps 
1) 
![image](https://user-images.githubusercontent.com/38582609/48176176-ef32c600-e349-11e8-9682-4588a189e4d3.png)
2) 
![image](https://user-images.githubusercontent.com/38582609/48176213-14273900-e34a-11e8-8d4e-684c9dfb0951.png)
but at step 2 android studio Failed to resolve: io.scanbot:sdk-package-1:1.38.2

please help me

**Comment by eddyfrank** [comment]
You have to add the maven repos in the section `allprojects` and *not* in `buildscript`.

top-level `build.gradle` file:

```
allprojects {
...
  repositories {
      google()
      jcenter()
      mavenCentral()

      // scanbot sdk repos
      maven {
          url 'https://nexus.scanbot.io/nexus/content/repositories/releases/'
      }
      maven {
          url 'https://nexus.scanbot.io/nexus/content/repositories/snapshots/'
      }
  }
...
}
```

Compare to our example app https://github.com/doo/scanbot-sdk-example-android/blob/master/ScanbotSDKexample/build.gradle#L16

Please also check
- Gradle docs - https://docs.gradle.org/current/userguide/introduction_dependency_management.html
- Android Studio docs - https://developer.android.com/studio/build/
