### ISSUE TITLE
No response from cheque scanning api

### ISSUE THREAD

**Issue by suzanneong3** [doo/scanbot-sdk-example-android#86]
Hi, what am I suppose to expect from this cheque scanning API? Is it able to pick up the cheque barcode? Because there is no response when I run the code... What code do I need to add in for it to work?

![image](https://user-images.githubusercontent.com/38582609/48592526-bfa43f00-e983-11e8-9e1b-172a8d10cc5d.png)

**Comment by tailsu** [comment]
The cheque recognizer reads the routing and account numbers from the bottom of the cheque form. It requires you however to hold the cheque horizontally, not vertically as in the screenshot above.

**Comment by eddyfrank** [comment]
We haven't received any updates on this issue and are assuming that this is solved.
