### ISSUE TITLE
Update SDK to use with AndroidX Packages 

### ISSUE THREAD

**Issue by MDXDave** [doo/scanbot-sdk-example-android#87]
As already mentioned in issue #75 the scanbot sdk does not work with AndroidX.

AndroidX packages are stable since [September 21st](https://developer.android.com/jetpack/androidx/androidx-rn#1.0.0), please update the sdk.

Going back to use Android-Support-Libs is not a alternative.

Dot mer dr Jefalle, Lück. 😉

**Comment by tailsu** [comment]
Hi,

We are already finished with the AndroidX integration and right now we're testing it internally. It will be made available with the next SDK release.

**Comment by eddyfrank** [comment]
Updated to AndroidX in version **1.40.0**.
See the [Release History](https://github.com/doo/scanbot-sdk-example-android/wiki/Release-History#1400) for a full changelog and check out the updated example apps in this repo.
