### ISSUE TITLE
migration to version 1.40.0

### ISSUE THREAD

**Issue by yassineKharraz** [doo/scanbot-sdk-example-android#92]
hello guys ,

I am using scanbot SDK for the first time and I am building a demo for my compagnie. 
everything works fine until I am upgrading from the 1.38.0 version to the latest one which is 1.40.0. it seems there is a confusion somewhere.

here is a screen shot of my build stack. Please help !! 
![capture](https://user-images.githubusercontent.com/6676529/50001887-9dabd580-ff9e-11e8-9c89-0ed0ab14f388.PNG)

**Comment by lebedevsd1** [comment]
Please refer to following articles:
[Gradle official documentation](https://docs.gradle.org/current/userguide/dependency_management_for_java_projects.html)
[stackoverflow](https://stackoverflow.com/questions/48462550/android-studio-build-gradle-warning-message)

**Comment by eddyfrank** [comment]
We haven't received a response to this issue and are assuming that this is solved.
