### ISSUE TITLE
OCR-Sanskrit Recognition 

### ISSUE THREAD

**Issue by darohar** [doo/scanbot-sdk-example-android#95]
What language to select for Sanskrit recognition Language.SAN is not available in Language.class

**Comment by eddyfrank** [comment]
Thanks for the report. Looks like the mapping for Sanskrit is missing in our Language enum class.
We will add it in the next SDK release.

**Comment by darohar** [comment]
Thanks for replying !! Can i get a tentative date of the next SDK release, my project is kind of stuck in the middle

**Comment by eddyfrank** [comment]
We are already working on the next SDK release, which will include a fix for that. Currently there is no ETA yet.
If you are a paying customer or developing for a customer, please reach out to sdk@scanbot.io for more details about our roadmap. Thanks.
However, we will post an update here as soon as we have published a new release.

**Comment by eddyfrank** [comment]
Support for Sanskrit (`Language.SAN`) was added in the recent version **1.50.0** of the Scanbot SDK. Please note the full changelog, especially the changes regarding the upgrade to Tesseract 4 and new language files:
https://github.com/doo/scanbot-sdk-example-android/wiki/Release-History
