### ISSUE TITLE
OCR - Hindi producing gibberish text 

### ISSUE THREAD

**Issue by darohar** [doo/scanbot-sdk-example-android#96]
Tried to perform OCR on Hindi text it is giving irrelevant text !!

**Comment by eddyfrank** [comment]
@darohar Could you please provide more details, like 
- example image
- which language file and configuration (sample code) did you take
- etc.
Thanks.

**Comment by eddyfrank** [comment]
Please give another try with the latest version **1.50.0** of the Scanbot SDK:
https://github.com/doo/scanbot-sdk-example-android/wiki/Release-History
