### ISSUE TITLE
When i scanned the Indian passport i can't able to get the Nationality?

### ISSUE THREAD

**Issue by bramkrishnareddy53** [doo/scanbot-sdk-example-android#97]
When i scanned the Indian passport i can't able to get the Nationality?. But i am getting rest of values can anyone please let me know this issue.. thanks in advance

**Comment by tailsu** [comment]
We have tests with Indian passports and there the nationality is correctly extracted. Of course, there might be a bug that is triggered by your specific document. I suggest that you contact us directly at sdk@scanbot.io where we'll be able to help you better.
